### PR TITLE
Default to start date if state isnt present

### LINKED ISSUE #3: Tap does not work standalone neither with meltano
Hi, I'm trying out this tap via Meltano (it is listed here: https://hub.meltano.com/extractors/tap-postmark/), and it errors on first run. It seems to always need to have a json state file before first run, rather than Meltano creating it in a database automatically (as others do).

I've then tried to run the tap manually as described in the readme, and it still does not work, giving this error:

```shell
mathieu@OTA-Mathieu-MBP-7MD6R otainsight % tap-postmark --state extract/tap-postmark.state.json -c postmark_config.json | target-json >> state_result.json
INFO >>> Running tap-postmark v0.1.0
CRITICAL module 'singer.metadata' has no attribute 'get_standard_metadata'
Traceback (most recent call last):
  File "/Users/mathieu/.pyenv/versions/3.9.9/bin/tap-postmark", line 8, in <module>
    sys.exit(main())
  File "/Users/mathieu/.pyenv/versions/3.9.9/lib/python3.9/site-packages/singer/utils.py", line 181, in wrapped
    return fn(*args, **kwargs)
  File "/Users/mathieu/.pyenv/versions/3.9.9/lib/python3.9/site-packages/tap_postmark/tap.py", line 42, in main
    catalog = discover()
  File "/Users/mathieu/.pyenv/versions/3.9.9/lib/python3.9/site-packages/tap_postmark/discover.py", line 23, in discover
    mdata: list = metadata.get_standard_metadata(
AttributeError: module 'singer.metadata' has no attribute 'get_standard_metadata'
```

### PR DESCRIPTION
**Pull request by pnadolny13**
Fixes https://github.com/Yoast/singer-tap-postmark/issues/3

### CODE REVIEW

**Comment by ReubenFrankel** [comment]
[Related discussion in Meltano Slack](https://meltano.slack.com/archives/C01TCRBBJD7/p1679232195743209)

**Comment by pnadolny13** [comment]
Hey @hongleivanyoast @brent-yoast! Are one of you able to review this bug fix?

**Comment by pnadolny13** [comment]
@hongleivanyoast @brent-yoast @michaelcoolen do one of you have a few minutes to review this PR?

**Comment by edgarrmondragon** [comment]
Thanks for merging @hongleivanyoast!

**Pull request merged**
